# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bag_feature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bag_feature.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x62\x61g_feature.proto\"n\n\x07OneShot\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12+\n\x11obstacles_feature\x18\x02 \x03(\x0b\x32\x10.ObstacleFeature\x12#\n\rlanes_feature\x18\x03 \x03(\x0b\x32\x0c.LaneFeature\"\x97\x03\n\x0fObstacleFeature\x12\x10\n\x08track_id\x18\x01 \x01(\r\x12+\n\x04type\x18\x02 \x01(\x0e\x32\x1d.ObstacleFeature.ObstacleType\x12\x1f\n\x08position\x18\x03 \x03(\x0b\x32\r.PositionInfo\x12\x32\n\x0c\x62\x65havior_tag\x18\x04 \x01(\x0e\x32\x1c.ObstacleFeature.BehaviorTag\"L\n\x0cObstacleType\x12\x0b\n\x07GENERAL\x10\x00\x12\x07\n\x03\x43\x41R\x10\x01\x12\t\n\x05TRUCK\x10\x02\x12\x0b\n\x07\x43YCLIST\x10\x03\x12\x0e\n\nPEDESTRAIN\x10\x04\"\xa1\x01\n\x0b\x42\x65haviorTag\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nRIGHT_TURN\x10\x01\x12\r\n\tLEFT_TURN\x10\x02\x12\x10\n\x0c\x41\x43\x43\x45LERATION\x10\x03\x12\x10\n\x0c\x44\x45\x43\x45LERATION\x10\x04\x12\x08\n\x04STOP\x10\x05\x12\t\n\x05START\x10\x06\x12\x0f\n\x0bLEFT_CHANGE\x10\x07\x12\x10\n\x0cRIGHT_CHANGE\x10\x08\x12\n\n\x06U_TURN\x10\t\"8\n\x0cPositionInfo\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x12\n\ntime_stamp\x18\x03 \x01(\x01\"!\n\tLanePoint\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\x91\x02\n\x0bLaneFeature\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\n\n\x02id\x18\x02 \x01(\r\x12\x19\n\x05point\x18\x03 \x03(\x0b\x32\n.LanePoint\x12\x1f\n\x04type\x18\x04 \x01(\x0e\x32\x11.LaneFeature.Type\"\xa6\x01\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rSINGLE_DASHED\x10\x01\x12\x11\n\rDOUBLE_DASHED\x10\x02\x12\x10\n\x0c\x44OUBLE_SOLID\x10\x03\x12\x10\n\x0cSINGLE_SOLID\x10\x04\x12\x1b\n\x17RIGHT_SOLID_LEFT_DASHED\x10\x05\x12\x1b\n\x17LEFT_SOLID_RIGHT_DASHED\x10\x06\x12\r\n\tROAD_EDGE\x10\x07\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_OBSTACLEFEATURE_OBSTACLETYPE = _descriptor.EnumDescriptor(
  name='ObstacleType',
  full_name='ObstacleFeature.ObstacleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GENERAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRUCK', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CYCLIST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PEDESTRAIN', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=301,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_OBSTACLEFEATURE_OBSTACLETYPE)

_OBSTACLEFEATURE_BEHAVIORTAG = _descriptor.EnumDescriptor(
  name='BehaviorTag',
  full_name='ObstacleFeature.BehaviorTag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_TURN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_TURN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCELERATION', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECELERATION', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_CHANGE', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_CHANGE', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='U_TURN', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=380,
  serialized_end=541,
)
_sym_db.RegisterEnumDescriptor(_OBSTACLEFEATURE_BEHAVIORTAG)

_LANEFEATURE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='LaneFeature.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINGLE_DASHED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE_DASHED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE_SOLID', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINGLE_SOLID', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_SOLID_LEFT_DASHED', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_SOLID_RIGHT_DASHED', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROAD_EDGE', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=744,
  serialized_end=910,
)
_sym_db.RegisterEnumDescriptor(_LANEFEATURE_TYPE)


_ONESHOT = _descriptor.Descriptor(
  name='OneShot',
  full_name='OneShot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='OneShot.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obstacles_feature', full_name='OneShot.obstacles_feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lanes_feature', full_name='OneShot.lanes_feature', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=131,
)


_OBSTACLEFEATURE = _descriptor.Descriptor(
  name='ObstacleFeature',
  full_name='ObstacleFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='track_id', full_name='ObstacleFeature.track_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ObstacleFeature.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='ObstacleFeature.position', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='behavior_tag', full_name='ObstacleFeature.behavior_tag', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OBSTACLEFEATURE_OBSTACLETYPE,
    _OBSTACLEFEATURE_BEHAVIORTAG,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=541,
)


_POSITIONINFO = _descriptor.Descriptor(
  name='PositionInfo',
  full_name='PositionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PositionInfo.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='PositionInfo.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='PositionInfo.time_stamp', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=599,
)


_LANEPOINT = _descriptor.Descriptor(
  name='LanePoint',
  full_name='LanePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='LanePoint.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='LanePoint.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=634,
)


_LANEFEATURE = _descriptor.Descriptor(
  name='LaneFeature',
  full_name='LaneFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='LaneFeature.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='LaneFeature.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='LaneFeature.point', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='LaneFeature.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LANEFEATURE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=637,
  serialized_end=910,
)

_ONESHOT.fields_by_name['obstacles_feature'].message_type = _OBSTACLEFEATURE
_ONESHOT.fields_by_name['lanes_feature'].message_type = _LANEFEATURE
_OBSTACLEFEATURE.fields_by_name['type'].enum_type = _OBSTACLEFEATURE_OBSTACLETYPE
_OBSTACLEFEATURE.fields_by_name['position'].message_type = _POSITIONINFO
_OBSTACLEFEATURE.fields_by_name['behavior_tag'].enum_type = _OBSTACLEFEATURE_BEHAVIORTAG
_OBSTACLEFEATURE_OBSTACLETYPE.containing_type = _OBSTACLEFEATURE
_OBSTACLEFEATURE_BEHAVIORTAG.containing_type = _OBSTACLEFEATURE
_LANEFEATURE.fields_by_name['point'].message_type = _LANEPOINT
_LANEFEATURE.fields_by_name['type'].enum_type = _LANEFEATURE_TYPE
_LANEFEATURE_TYPE.containing_type = _LANEFEATURE
DESCRIPTOR.message_types_by_name['OneShot'] = _ONESHOT
DESCRIPTOR.message_types_by_name['ObstacleFeature'] = _OBSTACLEFEATURE
DESCRIPTOR.message_types_by_name['PositionInfo'] = _POSITIONINFO
DESCRIPTOR.message_types_by_name['LanePoint'] = _LANEPOINT
DESCRIPTOR.message_types_by_name['LaneFeature'] = _LANEFEATURE

OneShot = _reflection.GeneratedProtocolMessageType('OneShot', (_message.Message,), dict(
  DESCRIPTOR = _ONESHOT,
  __module__ = 'bag_feature_pb2'
  # @@protoc_insertion_point(class_scope:OneShot)
  ))
_sym_db.RegisterMessage(OneShot)

ObstacleFeature = _reflection.GeneratedProtocolMessageType('ObstacleFeature', (_message.Message,), dict(
  DESCRIPTOR = _OBSTACLEFEATURE,
  __module__ = 'bag_feature_pb2'
  # @@protoc_insertion_point(class_scope:ObstacleFeature)
  ))
_sym_db.RegisterMessage(ObstacleFeature)

PositionInfo = _reflection.GeneratedProtocolMessageType('PositionInfo', (_message.Message,), dict(
  DESCRIPTOR = _POSITIONINFO,
  __module__ = 'bag_feature_pb2'
  # @@protoc_insertion_point(class_scope:PositionInfo)
  ))
_sym_db.RegisterMessage(PositionInfo)

LanePoint = _reflection.GeneratedProtocolMessageType('LanePoint', (_message.Message,), dict(
  DESCRIPTOR = _LANEPOINT,
  __module__ = 'bag_feature_pb2'
  # @@protoc_insertion_point(class_scope:LanePoint)
  ))
_sym_db.RegisterMessage(LanePoint)

LaneFeature = _reflection.GeneratedProtocolMessageType('LaneFeature', (_message.Message,), dict(
  DESCRIPTOR = _LANEFEATURE,
  __module__ = 'bag_feature_pb2'
  # @@protoc_insertion_point(class_scope:LaneFeature)
  ))
_sym_db.RegisterMessage(LaneFeature)


# @@protoc_insertion_point(module_scope)
