# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error_info.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='error_info.proto',
  package='haomo.hidelivery.guard',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10\x65rror_info.proto\x12\x16haomo.hidelivery.guard\"\x1a\n\tStackInfo\x12\r\n\x05stack\x18\x01 \x03(\t\"b\n\x08\x43oreInfo\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x04\x12\x35\n\nstack_info\x18\x03 \x01(\x0b\x32!.haomo.hidelivery.guard.StackInfo\"T\n\nSyslogInfo\x12\x12\n\nstart_time\x18\x01 \x01(\x04\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x04\x12\x0e\n\x06syslog\x18\x03 \x01(\t\x12\x10\n\x08kern_log\x18\x04 \x01(\t\"\x9d\x02\n\x07\x45rrInfo\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x04\x12\x0f\n\x07timeout\x18\x03 \x01(\x04\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12-\n\x05level\x18\x05 \x01(\x0e\x32\x1e.haomo.hidelivery.guard.PLevel\x12\x0b\n\x03src\x18\x06 \x01(\t\x12-\n\x04type\x18\x07 \x01(\x0e\x32\x1f.haomo.hidelivery.guard.SrcType\x12\x33\n\tcore_info\x18\x0b \x01(\x0b\x32 .haomo.hidelivery.guard.CoreInfo\x12\x37\n\x0bsyslog_info\x18\x0c \x01(\x0b\x32\".haomo.hidelivery.guard.SyslogInfo*\xce\x01\n\x06PLevel\x12\x05\n\x01W\x10\x00\x12\x06\n\x02P1\x10\x01\x12\x06\n\x02P0\x10\x02\x12\x0b\n\x07WARNING\x10\x0b\x12\x1a\n\x16\x46UNCTIONAL_DEGRADATION\x10\x0c\x12\x15\n\x11\x44RIVER_ONLINE_REQ\x10\r\x12\x17\n\x13\x44RIVER_TAKEOVER_REQ\x10\x0e\x12\x15\n\x11MRC_ROADSIDE_STOP\x10\x0f\x12\x11\n\rMRC_SLOW_STOP\x10\x10\x12\x16\n\x12MRC_EMERGENCY_STOP\x10\x11\x12\x12\n\x0e\x45XIT_AUTOPILOT\x10\x12*.\n\x07SrcType\x12\x08\n\x04\x45XEC\x10\x00\x12\x06\n\x02\x44S\x10\x01\x12\x08\n\x04\x44\x41TA\x10\x02\x12\x07\n\x03LIB\x10\x03\x62\x06proto3'
)

_PLEVEL = _descriptor.EnumDescriptor(
  name='PLevel',
  full_name='haomo.hidelivery.guard.PLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='W', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P0', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=3, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUNCTIONAL_DEGRADATION', index=4, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRIVER_ONLINE_REQ', index=5, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRIVER_TAKEOVER_REQ', index=6, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MRC_ROADSIDE_STOP', index=7, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MRC_SLOW_STOP', index=8, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MRC_EMERGENCY_STOP', index=9, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT_AUTOPILOT', index=10, number=18,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=547,
  serialized_end=753,
)
_sym_db.RegisterEnumDescriptor(_PLEVEL)

PLevel = enum_type_wrapper.EnumTypeWrapper(_PLEVEL)
_SRCTYPE = _descriptor.EnumDescriptor(
  name='SrcType',
  full_name='haomo.hidelivery.guard.SrcType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXEC', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIB', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=755,
  serialized_end=801,
)
_sym_db.RegisterEnumDescriptor(_SRCTYPE)

SrcType = enum_type_wrapper.EnumTypeWrapper(_SRCTYPE)
W = 0
P1 = 1
P0 = 2
WARNING = 11
FUNCTIONAL_DEGRADATION = 12
DRIVER_ONLINE_REQ = 13
DRIVER_TAKEOVER_REQ = 14
MRC_ROADSIDE_STOP = 15
MRC_SLOW_STOP = 16
MRC_EMERGENCY_STOP = 17
EXIT_AUTOPILOT = 18
EXEC = 0
DS = 1
DATA = 2
LIB = 3



_STACKINFO = _descriptor.Descriptor(
  name='StackInfo',
  full_name='haomo.hidelivery.guard.StackInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stack', full_name='haomo.hidelivery.guard.StackInfo.stack', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=70,
)


_COREINFO = _descriptor.Descriptor(
  name='CoreInfo',
  full_name='haomo.hidelivery.guard.CoreInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='haomo.hidelivery.guard.CoreInfo.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='haomo.hidelivery.guard.CoreInfo.time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stack_info', full_name='haomo.hidelivery.guard.CoreInfo.stack_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=170,
)


_SYSLOGINFO = _descriptor.Descriptor(
  name='SyslogInfo',
  full_name='haomo.hidelivery.guard.SyslogInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='haomo.hidelivery.guard.SyslogInfo.start_time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='haomo.hidelivery.guard.SyslogInfo.end_time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='syslog', full_name='haomo.hidelivery.guard.SyslogInfo.syslog', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kern_log', full_name='haomo.hidelivery.guard.SyslogInfo.kern_log', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=256,
)


_ERRINFO = _descriptor.Descriptor(
  name='ErrInfo',
  full_name='haomo.hidelivery.guard.ErrInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='haomo.hidelivery.guard.ErrInfo.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='haomo.hidelivery.guard.ErrInfo.time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='haomo.hidelivery.guard.ErrInfo.timeout', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='haomo.hidelivery.guard.ErrInfo.msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='haomo.hidelivery.guard.ErrInfo.level', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src', full_name='haomo.hidelivery.guard.ErrInfo.src', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='haomo.hidelivery.guard.ErrInfo.type', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core_info', full_name='haomo.hidelivery.guard.ErrInfo.core_info', index=7,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='syslog_info', full_name='haomo.hidelivery.guard.ErrInfo.syslog_info', index=8,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=544,
)

_COREINFO.fields_by_name['stack_info'].message_type = _STACKINFO
_ERRINFO.fields_by_name['level'].enum_type = _PLEVEL
_ERRINFO.fields_by_name['type'].enum_type = _SRCTYPE
_ERRINFO.fields_by_name['core_info'].message_type = _COREINFO
_ERRINFO.fields_by_name['syslog_info'].message_type = _SYSLOGINFO
DESCRIPTOR.message_types_by_name['StackInfo'] = _STACKINFO
DESCRIPTOR.message_types_by_name['CoreInfo'] = _COREINFO
DESCRIPTOR.message_types_by_name['SyslogInfo'] = _SYSLOGINFO
DESCRIPTOR.message_types_by_name['ErrInfo'] = _ERRINFO
DESCRIPTOR.enum_types_by_name['PLevel'] = _PLEVEL
DESCRIPTOR.enum_types_by_name['SrcType'] = _SRCTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StackInfo = _reflection.GeneratedProtocolMessageType('StackInfo', (_message.Message,), {
  'DESCRIPTOR' : _STACKINFO,
  '__module__' : 'error_info_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.guard.StackInfo)
  })
_sym_db.RegisterMessage(StackInfo)

CoreInfo = _reflection.GeneratedProtocolMessageType('CoreInfo', (_message.Message,), {
  'DESCRIPTOR' : _COREINFO,
  '__module__' : 'error_info_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.guard.CoreInfo)
  })
_sym_db.RegisterMessage(CoreInfo)

SyslogInfo = _reflection.GeneratedProtocolMessageType('SyslogInfo', (_message.Message,), {
  'DESCRIPTOR' : _SYSLOGINFO,
  '__module__' : 'error_info_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.guard.SyslogInfo)
  })
_sym_db.RegisterMessage(SyslogInfo)

ErrInfo = _reflection.GeneratedProtocolMessageType('ErrInfo', (_message.Message,), {
  'DESCRIPTOR' : _ERRINFO,
  '__module__' : 'error_info_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.guard.ErrInfo)
  })
_sym_db.RegisterMessage(ErrInfo)


# @@protoc_insertion_point(module_scope)
