# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fsm.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fsm.proto',
  package='haomo.hidelivery.fsm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tfsm.proto\x12\x14haomo.hidelivery.fsm\x1a\x0cheader.proto\"\xb0\x02\n\tFsmOutput\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.haomo.hios.Header\x12\x13\n\x0bsys_time_us\x18\x02 \x01(\x04\x12\x31\n\tfsm_state\x18\x03 \x01(\x0e\x32\x1e.haomo.hidelivery.fsm.FsmState\x12\x34\n\x0c\x66sm_substate\x18\x04 \x01(\x0e\x32\x1e.haomo.hidelivery.fsm.FsmState\x12\x15\n\rfailure_error\x18\x06 \x01(\t\x12\x1b\n\x13\x66\x61ilure_error_stamp\x18\x07 \x01(\x04\x12\x13\n\x0b\x63heck_rules\x18\x08 \x03(\t\x12\x38\n\x10\x66sm_pre_substate\x18\t \x01(\x0e\x32\x1e.haomo.hidelivery.fsm.FsmState*\xc9\x03\n\x08\x46smState\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05READY\x10\x01\x12\x07\n\x03OFF\x10\x02\x12\x0e\n\nIPC_ACTIVE\x10\x03\x12\x0b\n\x07STANDBY\x10\x04\x12\x0f\n\x0b\x41\x44S_STANDBY\x10\x05\x12\n\n\x06REMOTE\x10\x06\x12\x10\n\x0cREMOTE_DRIVE\x10\x07\x12\x12\n\x0eREMOTE_ARRIVED\x10\x08\x12\x0e\n\nADS_ACTIVE\x10\t\x12\n\n\x06\x41\x44S_ON\x10\n\x12\n\n\x06\x43RUISE\x10\x0b\x12\x0f\n\x0b\x41\x44S_ARRIVED\x10\x0c\x12\r\n\tOBS_BRAKE\x10\r\x12\t\n\x05\x42LOCK\x10\x0e\x12\t\n\x05\x41VOID\x10\x0f\x12\x0c\n\x08\x41\x42NORMAL\x10\x10\x12\x0f\n\x0b\x41\x44S_FAILURE\x10\x11\x12\x07\n\x03OTA\x10\x12\x12\n\n\x06OTAING\x10\x13\x12\x10\n\x0cOTA_FINISHED\x10\x14\x12\x08\n\x04\x45XIT\x10\x15\x12\x0b\n\x07\x41\x44S_OFF\x10\x16\x12\x10\n\x0c\x43LOUD_REMOTE\x10\x17\x12\x0f\n\x0b\x43LOUD_DRIVE\x10\x18\x12\x0e\n\nCLOUD_STOP\x10\x19\x12\x0f\n\x0b\x43LOUD_ESTOP\x10\x1a\x12\r\n\tNEAR_STOP\x10\x1b\x12\t\n\x05\x45STOP\x10\x1c\x12\x10\n\x0cSTOP_RECOVER\x10\x1d\x12\x11\n\rRECOVER_ESTOP\x10\x1e\x62\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,])

_FSMSTATE = _descriptor.EnumDescriptor(
  name='FsmState',
  full_name='haomo.hidelivery.fsm.FsmState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPC_ACTIVE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STANDBY', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADS_STANDBY', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOTE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOTE_DRIVE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOTE_ARRIVED', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADS_ACTIVE', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADS_ON', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRUISE', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADS_ARRIVED', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBS_BRAKE', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCK', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVOID', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABNORMAL', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADS_FAILURE', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTA', index=18, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTAING', index=19, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTA_FINISHED', index=20, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=21, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADS_OFF', index=22, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUD_REMOTE', index=23, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUD_DRIVE', index=24, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUD_STOP', index=25, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUD_ESTOP', index=26, number=26,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEAR_STOP', index=27, number=27,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ESTOP', index=28, number=28,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_RECOVER', index=29, number=29,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECOVER_ESTOP', index=30, number=30,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=357,
  serialized_end=814,
)
_sym_db.RegisterEnumDescriptor(_FSMSTATE)

FsmState = enum_type_wrapper.EnumTypeWrapper(_FSMSTATE)
DEFAULT = 0
READY = 1
OFF = 2
IPC_ACTIVE = 3
STANDBY = 4
ADS_STANDBY = 5
REMOTE = 6
REMOTE_DRIVE = 7
REMOTE_ARRIVED = 8
ADS_ACTIVE = 9
ADS_ON = 10
CRUISE = 11
ADS_ARRIVED = 12
OBS_BRAKE = 13
BLOCK = 14
AVOID = 15
ABNORMAL = 16
ADS_FAILURE = 17
OTA = 18
OTAING = 19
OTA_FINISHED = 20
EXIT = 21
ADS_OFF = 22
CLOUD_REMOTE = 23
CLOUD_DRIVE = 24
CLOUD_STOP = 25
CLOUD_ESTOP = 26
NEAR_STOP = 27
ESTOP = 28
STOP_RECOVER = 29
RECOVER_ESTOP = 30



_FSMOUTPUT = _descriptor.Descriptor(
  name='FsmOutput',
  full_name='haomo.hidelivery.fsm.FsmOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='haomo.hidelivery.fsm.FsmOutput.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sys_time_us', full_name='haomo.hidelivery.fsm.FsmOutput.sys_time_us', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fsm_state', full_name='haomo.hidelivery.fsm.FsmOutput.fsm_state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fsm_substate', full_name='haomo.hidelivery.fsm.FsmOutput.fsm_substate', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failure_error', full_name='haomo.hidelivery.fsm.FsmOutput.failure_error', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failure_error_stamp', full_name='haomo.hidelivery.fsm.FsmOutput.failure_error_stamp', index=5,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='check_rules', full_name='haomo.hidelivery.fsm.FsmOutput.check_rules', index=6,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fsm_pre_substate', full_name='haomo.hidelivery.fsm.FsmOutput.fsm_pre_substate', index=7,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=354,
)

_FSMOUTPUT.fields_by_name['header'].message_type = header__pb2._HEADER
_FSMOUTPUT.fields_by_name['fsm_state'].enum_type = _FSMSTATE
_FSMOUTPUT.fields_by_name['fsm_substate'].enum_type = _FSMSTATE
_FSMOUTPUT.fields_by_name['fsm_pre_substate'].enum_type = _FSMSTATE
DESCRIPTOR.message_types_by_name['FsmOutput'] = _FSMOUTPUT
DESCRIPTOR.enum_types_by_name['FsmState'] = _FSMSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FsmOutput = _reflection.GeneratedProtocolMessageType('FsmOutput', (_message.Message,), {
  'DESCRIPTOR' : _FSMOUTPUT,
  '__module__' : 'fsm_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.fsm.FsmOutput)
  })
_sym_db.RegisterMessage(FsmOutput)


# @@protoc_insertion_point(module_scope)
