# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghd_message.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import adasisv3_pb2 as adasisv3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghd_message.proto',
  package='haomo.hipilot.localization',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11ghd_message.proto\x12\x1ahaomo.hipilot.localization\x1a\x0cheader.proto\x1a\x0e\x61\x64\x61sisv3.proto\"\xed\x01\n\x11MessageOnBusHaomo\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.haomo.hios.Header\x12\x13\n\x0bsys_time_us\x18\x02 \x01(\x04\x12\x38\n\x12ghd_message_on_bus\x18\x03 \x03(\x0b\x32\x1c.ehp.adasisv3cc.MessageOnBus\x12\x12\n\nota_status\x18\x04 \x01(\x05\x12\x42\n\x0f\x64iagnosis_codes\x18\x05 \x03(\x0e\x32).haomo.hipilot.localization.DiagnosisType\x12\r\n\x05state\x18\x06 \x01(\r*\x93\x06\n\rDiagnosisType\x12\x1e\n\x1a\x44IAGNOSIS_TYPE_DEFAULT_ADD\x10\x00\x12\x1f\n\x1b\x44IAGNOSIS_TYPE_SYSTEM_FAULT\x10\x01\x12\x1c\n\x18\x44IAGNOSIS_TYPE_UID_FAULT\x10\x02\x12\x1c\n\x18\x44IAGNOSIS_TYPE_ROM_ERROR\x10\x03\x12\x1d\n\x19\x44IAGNOSIS_TYPE_PATH_ERROR\x10\x04\x12\"\n\x1e\x44IAGNOSIS_TYPE_FILE_AUTH_FAULT\x10\x05\x12\x1e\n\x1a\x44IAGNOSIS_TYPE_HDMAP_FAULT\x10\x64\x12)\n$DIAGNOSIS_TYPE_RECEIVE_MESSAGE_FAULT\x10\xc8\x01\x12&\n!DIAGNOSIS_TYPE_SEND_MESSAGE_FAULT\x10\xc9\x01\x12$\n\x1f\x44IAGNOSIS_TYPE_POS_SIGNAL_FAULT\x10\xac\x02\x12#\n\x1e\x44IAGNOSIS_TYPE_GNSS_LOST_FAULT\x10\xae\x02\x12&\n!DIAGNOSIS_TYPE_GNSS_INVALID_FAULT\x10\xaf\x02\x12\"\n\x1d\x44IAGNOSIS_TYPE_ACC_LOST_FAULT\x10\xb5\x02\x12%\n DIAGNOSIS_TYPE_ACC_INVALID_FAULT\x10\xb6\x02\x12#\n\x1e\x44IAGNOSIS_TYPE_GYRO_LOST_FAULT\x10\xbc\x02\x12&\n!DIAGNOSIS_TYPE_GYRO_INVALID_FAULT\x10\xbd\x02\x12$\n\x1f\x44IAGNOSIS_TYPE_PULSE_LOST_FAULT\x10\xc3\x02\x12\'\n\"DIAGNOSIS_TYPE_PULSE_INVALID_FAULT\x10\xc4\x02\x12%\n DIAGNOSIS_TYPE_CAMERA_LOST_FAULT\x10\xca\x02\x12(\n#DIAGNOSIS_TYPE_CAMERA_INVALID_FAULT\x10\xcb\x02\x12$\n\x1f\x44IAGNOSIS_TYPE_ACTIVATION_FAULT\x10\x90\x03\x62\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,adasisv3__pb2.DESCRIPTOR,])

_DIAGNOSISTYPE = _descriptor.EnumDescriptor(
  name='DiagnosisType',
  full_name='haomo.hipilot.localization.DiagnosisType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_DEFAULT_ADD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_SYSTEM_FAULT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_UID_FAULT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_ROM_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_PATH_ERROR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_FILE_AUTH_FAULT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_HDMAP_FAULT', index=6, number=100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_RECEIVE_MESSAGE_FAULT', index=7, number=200,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_SEND_MESSAGE_FAULT', index=8, number=201,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_POS_SIGNAL_FAULT', index=9, number=300,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_GNSS_LOST_FAULT', index=10, number=302,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_GNSS_INVALID_FAULT', index=11, number=303,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_ACC_LOST_FAULT', index=12, number=309,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_ACC_INVALID_FAULT', index=13, number=310,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_GYRO_LOST_FAULT', index=14, number=316,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_GYRO_INVALID_FAULT', index=15, number=317,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_PULSE_LOST_FAULT', index=16, number=323,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_PULSE_INVALID_FAULT', index=17, number=324,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_CAMERA_LOST_FAULT', index=18, number=330,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_CAMERA_INVALID_FAULT', index=19, number=331,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSIS_TYPE_ACTIVATION_FAULT', index=20, number=400,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=320,
  serialized_end=1107,
)
_sym_db.RegisterEnumDescriptor(_DIAGNOSISTYPE)

DiagnosisType = enum_type_wrapper.EnumTypeWrapper(_DIAGNOSISTYPE)
DIAGNOSIS_TYPE_DEFAULT_ADD = 0
DIAGNOSIS_TYPE_SYSTEM_FAULT = 1
DIAGNOSIS_TYPE_UID_FAULT = 2
DIAGNOSIS_TYPE_ROM_ERROR = 3
DIAGNOSIS_TYPE_PATH_ERROR = 4
DIAGNOSIS_TYPE_FILE_AUTH_FAULT = 5
DIAGNOSIS_TYPE_HDMAP_FAULT = 100
DIAGNOSIS_TYPE_RECEIVE_MESSAGE_FAULT = 200
DIAGNOSIS_TYPE_SEND_MESSAGE_FAULT = 201
DIAGNOSIS_TYPE_POS_SIGNAL_FAULT = 300
DIAGNOSIS_TYPE_GNSS_LOST_FAULT = 302
DIAGNOSIS_TYPE_GNSS_INVALID_FAULT = 303
DIAGNOSIS_TYPE_ACC_LOST_FAULT = 309
DIAGNOSIS_TYPE_ACC_INVALID_FAULT = 310
DIAGNOSIS_TYPE_GYRO_LOST_FAULT = 316
DIAGNOSIS_TYPE_GYRO_INVALID_FAULT = 317
DIAGNOSIS_TYPE_PULSE_LOST_FAULT = 323
DIAGNOSIS_TYPE_PULSE_INVALID_FAULT = 324
DIAGNOSIS_TYPE_CAMERA_LOST_FAULT = 330
DIAGNOSIS_TYPE_CAMERA_INVALID_FAULT = 331
DIAGNOSIS_TYPE_ACTIVATION_FAULT = 400



_MESSAGEONBUSHAOMO = _descriptor.Descriptor(
  name='MessageOnBusHaomo',
  full_name='haomo.hipilot.localization.MessageOnBusHaomo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='haomo.hipilot.localization.MessageOnBusHaomo.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sys_time_us', full_name='haomo.hipilot.localization.MessageOnBusHaomo.sys_time_us', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ghd_message_on_bus', full_name='haomo.hipilot.localization.MessageOnBusHaomo.ghd_message_on_bus', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ota_status', full_name='haomo.hipilot.localization.MessageOnBusHaomo.ota_status', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagnosis_codes', full_name='haomo.hipilot.localization.MessageOnBusHaomo.diagnosis_codes', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='haomo.hipilot.localization.MessageOnBusHaomo.state', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=317,
)

_MESSAGEONBUSHAOMO.fields_by_name['header'].message_type = header__pb2._HEADER
_MESSAGEONBUSHAOMO.fields_by_name['ghd_message_on_bus'].message_type = adasisv3__pb2._MESSAGEONBUS
_MESSAGEONBUSHAOMO.fields_by_name['diagnosis_codes'].enum_type = _DIAGNOSISTYPE
DESCRIPTOR.message_types_by_name['MessageOnBusHaomo'] = _MESSAGEONBUSHAOMO
DESCRIPTOR.enum_types_by_name['DiagnosisType'] = _DIAGNOSISTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageOnBusHaomo = _reflection.GeneratedProtocolMessageType('MessageOnBusHaomo', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEONBUSHAOMO,
  '__module__' : 'ghd_message_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hipilot.localization.MessageOnBusHaomo)
  })
_sym_db.RegisterMessage(MessageOnBusHaomo)


# @@protoc_insertion_point(module_scope)
