# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hm_header.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hm_header.proto',
  package='haomo.hios',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0fhm_header.proto\x12\nhaomo.hios\"\xa3\x01\n\nSourceInfo\x12\x0b\n\x03seq\x18\x02 \x02(\x03\x12\r\n\x05stamp\x18\x03 \x02(\x04\x12\x32\n\x06source\x18\x04 \x03(\x0b\x32\".haomo.hios.SourceInfo.SourceEntry\x1a\x45\n\x0bSourceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.haomo.hios.SourceInfo:\x02\x38\x01\"\xfd\x01\n\x08HmHeader\x12\x0b\n\x03seq\x18\x01 \x02(\x03\x12\r\n\x05stamp\x18\x02 \x02(\x04\x12\x16\n\x0eoriginal_stamp\x18\x03 \x01(\x04\x12\x0e\n\x06length\x18\x04 \x01(\x07\x12\x1e\n\x13source_camera_stamp\x18\x05 \x01(\x04:\x01\x30\x12\x14\n\x05valid\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x30\n\x06source\x18\x07 \x03(\x0b\x32 .haomo.hios.HmHeader.SourceEntry\x1a\x45\n\x0bSourceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.haomo.hios.SourceInfo:\x02\x38\x01'
)




_SOURCEINFO_SOURCEENTRY = _descriptor.Descriptor(
  name='SourceEntry',
  full_name='haomo.hios.SourceInfo.SourceEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='haomo.hios.SourceInfo.SourceEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='haomo.hios.SourceInfo.SourceEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=195,
)

_SOURCEINFO = _descriptor.Descriptor(
  name='SourceInfo',
  full_name='haomo.hios.SourceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='haomo.hios.SourceInfo.seq', index=0,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamp', full_name='haomo.hios.SourceInfo.stamp', index=1,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='haomo.hios.SourceInfo.source', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SOURCEINFO_SOURCEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=195,
)


_HMHEADER_SOURCEENTRY = _descriptor.Descriptor(
  name='SourceEntry',
  full_name='haomo.hios.HmHeader.SourceEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='haomo.hios.HmHeader.SourceEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='haomo.hios.HmHeader.SourceEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=195,
)

_HMHEADER = _descriptor.Descriptor(
  name='HmHeader',
  full_name='haomo.hios.HmHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='haomo.hios.HmHeader.seq', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamp', full_name='haomo.hios.HmHeader.stamp', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='original_stamp', full_name='haomo.hios.HmHeader.original_stamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='haomo.hios.HmHeader.length', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_camera_stamp', full_name='haomo.hios.HmHeader.source_camera_stamp', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid', full_name='haomo.hios.HmHeader.valid', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='haomo.hios.HmHeader.source', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HMHEADER_SOURCEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=451,
)

_SOURCEINFO_SOURCEENTRY.fields_by_name['value'].message_type = _SOURCEINFO
_SOURCEINFO_SOURCEENTRY.containing_type = _SOURCEINFO
_SOURCEINFO.fields_by_name['source'].message_type = _SOURCEINFO_SOURCEENTRY
_HMHEADER_SOURCEENTRY.fields_by_name['value'].message_type = _SOURCEINFO
_HMHEADER_SOURCEENTRY.containing_type = _HMHEADER
_HMHEADER.fields_by_name['source'].message_type = _HMHEADER_SOURCEENTRY
DESCRIPTOR.message_types_by_name['SourceInfo'] = _SOURCEINFO
DESCRIPTOR.message_types_by_name['HmHeader'] = _HMHEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SourceInfo = _reflection.GeneratedProtocolMessageType('SourceInfo', (_message.Message,), {

  'SourceEntry' : _reflection.GeneratedProtocolMessageType('SourceEntry', (_message.Message,), {
    'DESCRIPTOR' : _SOURCEINFO_SOURCEENTRY,
    '__module__' : 'hm_header_pb2'
    # @@protoc_insertion_point(class_scope:haomo.hios.SourceInfo.SourceEntry)
    })
  ,
  'DESCRIPTOR' : _SOURCEINFO,
  '__module__' : 'hm_header_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hios.SourceInfo)
  })
_sym_db.RegisterMessage(SourceInfo)
_sym_db.RegisterMessage(SourceInfo.SourceEntry)

HmHeader = _reflection.GeneratedProtocolMessageType('HmHeader', (_message.Message,), {

  'SourceEntry' : _reflection.GeneratedProtocolMessageType('SourceEntry', (_message.Message,), {
    'DESCRIPTOR' : _HMHEADER_SOURCEENTRY,
    '__module__' : 'hm_header_pb2'
    # @@protoc_insertion_point(class_scope:haomo.hios.HmHeader.SourceEntry)
    })
  ,
  'DESCRIPTOR' : _HMHEADER,
  '__module__' : 'hm_header_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hios.HmHeader)
  })
_sym_db.RegisterMessage(HmHeader)
_sym_db.RegisterMessage(HmHeader.SourceEntry)


_SOURCEINFO_SOURCEENTRY._options = None
_HMHEADER_SOURCEENTRY._options = None
# @@protoc_insertion_point(module_scope)
