# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hmi_engine.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hmi_engine.proto',
  package='haomo.hipilot.hmi_engine',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10hmi_engine.proto\x12\x18haomo.hipilot.hmi_engine\x1a\x0cheader.proto\x1a\x0c\x63ommon.proto\"\xe1\x02\n\rHmiEngineData\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.haomo.hios.Header\x12\x12\n\nalc_enable\x18\x02 \x01(\x08\x12\x12\n\nnoh_enable\x18\x03 \x01(\x08\x12(\n intelligent_speed_control_enable\x18\x04 \x01(\x08\x12\x15\n\rcurrent_speed\x18\x05 \x01(\x01\x12\x14\n\x0c\x63ruise_speed\x18\x06 \x01(\x01\x12\x11\n\tnoh_state\x18\x07 \x01(\x08\x12\x12\n\nalc_cancel\x18\x08 \x01(\x08\x12\x1c\n\x14vetical_intervention\x18\t \x01(\x08\x12\x1c\n\x14lateral_intervention\x18\n \x01(\x08\x12$\n\x1cvetical_intervention_timeout\x18\x0b \x01(\x08\x12$\n\x1clateral_intervention_timeout\x18\x0c \x01(\x08\x62\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])




_HMIENGINEDATA = _descriptor.Descriptor(
  name='HmiEngineData',
  full_name='haomo.hipilot.hmi_engine.HmiEngineData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='haomo.hipilot.hmi_engine.HmiEngineData.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alc_enable', full_name='haomo.hipilot.hmi_engine.HmiEngineData.alc_enable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noh_enable', full_name='haomo.hipilot.hmi_engine.HmiEngineData.noh_enable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intelligent_speed_control_enable', full_name='haomo.hipilot.hmi_engine.HmiEngineData.intelligent_speed_control_enable', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_speed', full_name='haomo.hipilot.hmi_engine.HmiEngineData.current_speed', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cruise_speed', full_name='haomo.hipilot.hmi_engine.HmiEngineData.cruise_speed', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noh_state', full_name='haomo.hipilot.hmi_engine.HmiEngineData.noh_state', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alc_cancel', full_name='haomo.hipilot.hmi_engine.HmiEngineData.alc_cancel', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vetical_intervention', full_name='haomo.hipilot.hmi_engine.HmiEngineData.vetical_intervention', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lateral_intervention', full_name='haomo.hipilot.hmi_engine.HmiEngineData.lateral_intervention', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vetical_intervention_timeout', full_name='haomo.hipilot.hmi_engine.HmiEngineData.vetical_intervention_timeout', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lateral_intervention_timeout', full_name='haomo.hipilot.hmi_engine.HmiEngineData.lateral_intervention_timeout', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=428,
)

_HMIENGINEDATA.fields_by_name['header'].message_type = header__pb2._HEADER
DESCRIPTOR.message_types_by_name['HmiEngineData'] = _HMIENGINEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HmiEngineData = _reflection.GeneratedProtocolMessageType('HmiEngineData', (_message.Message,), {
  'DESCRIPTOR' : _HMIENGINEDATA,
  '__module__' : 'hmi_engine_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hipilot.hmi_engine.HmiEngineData)
  })
_sym_db.RegisterMessage(HmiEngineData)


# @@protoc_insertion_point(module_scope)
