# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='label.proto',
  package='haomo.hidelivery.guard',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0blabel.proto\x12\x16haomo.hidelivery.guard\x1a\x0cheader.proto\"@\n\tRangeData\x12\x12\n\nbegin_time\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\")\n\nMomentData\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xac\x01\n\x07LabelPb\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.haomo.hios.Header\x12\r\n\x05\x63\x61rid\x18\x02 \x01(\t\x12\x35\n\nrange_data\x18\x03 \x01(\x0b\x32!.haomo.hidelivery.guard.RangeData\x12\x37\n\x0bmoment_data\x18\x04 \x01(\x0b\x32\".haomo.hidelivery.guard.MomentDatab\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,])




_RANGEDATA = _descriptor.Descriptor(
  name='RangeData',
  full_name='haomo.hidelivery.guard.RangeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin_time', full_name='haomo.hidelivery.guard.RangeData.begin_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='haomo.hidelivery.guard.RangeData.end_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='haomo.hidelivery.guard.RangeData.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=117,
)


_MOMENTDATA = _descriptor.Descriptor(
  name='MomentData',
  full_name='haomo.hidelivery.guard.MomentData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='haomo.hidelivery.guard.MomentData.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='haomo.hidelivery.guard.MomentData.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=160,
)


_LABELPB = _descriptor.Descriptor(
  name='LabelPb',
  full_name='haomo.hidelivery.guard.LabelPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='haomo.hidelivery.guard.LabelPb.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carid', full_name='haomo.hidelivery.guard.LabelPb.carid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range_data', full_name='haomo.hidelivery.guard.LabelPb.range_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moment_data', full_name='haomo.hidelivery.guard.LabelPb.moment_data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=335,
)

_LABELPB.fields_by_name['header'].message_type = header__pb2._HEADER
_LABELPB.fields_by_name['range_data'].message_type = _RANGEDATA
_LABELPB.fields_by_name['moment_data'].message_type = _MOMENTDATA
DESCRIPTOR.message_types_by_name['RangeData'] = _RANGEDATA
DESCRIPTOR.message_types_by_name['MomentData'] = _MOMENTDATA
DESCRIPTOR.message_types_by_name['LabelPb'] = _LABELPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RangeData = _reflection.GeneratedProtocolMessageType('RangeData', (_message.Message,), {
  'DESCRIPTOR' : _RANGEDATA,
  '__module__' : 'label_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.guard.RangeData)
  })
_sym_db.RegisterMessage(RangeData)

MomentData = _reflection.GeneratedProtocolMessageType('MomentData', (_message.Message,), {
  'DESCRIPTOR' : _MOMENTDATA,
  '__module__' : 'label_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.guard.MomentData)
  })
_sym_db.RegisterMessage(MomentData)

LabelPb = _reflection.GeneratedProtocolMessageType('LabelPb', (_message.Message,), {
  'DESCRIPTOR' : _LABELPB,
  '__module__' : 'label_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.guard.LabelPb)
  })
_sym_db.RegisterMessage(LabelPb)


# @@protoc_insertion_point(module_scope)
