# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lidar_difop.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lidar_difop.proto',
  package='haomo.hidelivery',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11lidar_difop.proto\x12\x10haomo.hidelivery\x1a\x0cheader.proto\"\x8e\x01\n\x0cLidarDifopPb\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.haomo.hios.Header\x12\x38\n\x05pData\x18\x02 \x01(\x0b\x32).haomo.hidelivery.LidarDifopPb.packetData\x1a \n\npacketData\x12\x12\n\npacketdata\x18\x01 \x01(\x0c\x62\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,])




_LIDARDIFOPPB_PACKETDATA = _descriptor.Descriptor(
  name='packetData',
  full_name='haomo.hidelivery.LidarDifopPb.packetData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packetdata', full_name='haomo.hidelivery.LidarDifopPb.packetData.packetdata', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=196,
)

_LIDARDIFOPPB = _descriptor.Descriptor(
  name='LidarDifopPb',
  full_name='haomo.hidelivery.LidarDifopPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='haomo.hidelivery.LidarDifopPb.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pData', full_name='haomo.hidelivery.LidarDifopPb.pData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LIDARDIFOPPB_PACKETDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=196,
)

_LIDARDIFOPPB_PACKETDATA.containing_type = _LIDARDIFOPPB
_LIDARDIFOPPB.fields_by_name['header'].message_type = header__pb2._HEADER
_LIDARDIFOPPB.fields_by_name['pData'].message_type = _LIDARDIFOPPB_PACKETDATA
DESCRIPTOR.message_types_by_name['LidarDifopPb'] = _LIDARDIFOPPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LidarDifopPb = _reflection.GeneratedProtocolMessageType('LidarDifopPb', (_message.Message,), {

  'packetData' : _reflection.GeneratedProtocolMessageType('packetData', (_message.Message,), {
    'DESCRIPTOR' : _LIDARDIFOPPB_PACKETDATA,
    '__module__' : 'lidar_difop_pb2'
    # @@protoc_insertion_point(class_scope:haomo.hidelivery.LidarDifopPb.packetData)
    })
  ,
  'DESCRIPTOR' : _LIDARDIFOPPB,
  '__module__' : 'lidar_difop_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.LidarDifopPb)
  })
_sym_db.RegisterMessage(LidarDifopPb)
_sym_db.RegisterMessage(LidarDifopPb.packetData)


# @@protoc_insertion_point(module_scope)
