# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='log_data.proto',
  package='haomo.hidelivery',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0elog_data.proto\x12\x10haomo.hidelivery\x1a\x0cheader.proto\"<\n\tLogDataPb\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.haomo.hios.Header\x12\x0b\n\x03log\x18\x02 \x01(\tb\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,])




_LOGDATAPB = _descriptor.Descriptor(
  name='LogDataPb',
  full_name='haomo.hidelivery.LogDataPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='haomo.hidelivery.LogDataPb.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log', full_name='haomo.hidelivery.LogDataPb.log', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=110,
)

_LOGDATAPB.fields_by_name['header'].message_type = header__pb2._HEADER
DESCRIPTOR.message_types_by_name['LogDataPb'] = _LOGDATAPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogDataPb = _reflection.GeneratedProtocolMessageType('LogDataPb', (_message.Message,), {
  'DESCRIPTOR' : _LOGDATAPB,
  '__module__' : 'log_data_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.LogDataPb)
  })
_sym_db.RegisterMessage(LogDataPb)


# @@protoc_insertion_point(module_scope)
