# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ota_version_request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ota_version_request.proto',
  package='haomo.hidelivery.ota',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x19ota_version_request.proto\x12\x14haomo.hidelivery.ota\x1a\x0cheader.proto\"F\n\x10VersionRequestPb\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.haomo.hios.Header\x12\x0e\n\x06module\x18\x02 \x01(\tb\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,])




_VERSIONREQUESTPB = _descriptor.Descriptor(
  name='VersionRequestPb',
  full_name='haomo.hidelivery.ota.VersionRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='haomo.hidelivery.ota.VersionRequestPb.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module', full_name='haomo.hidelivery.ota.VersionRequestPb.module', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=135,
)

_VERSIONREQUESTPB.fields_by_name['header'].message_type = header__pb2._HEADER
DESCRIPTOR.message_types_by_name['VersionRequestPb'] = _VERSIONREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionRequestPb = _reflection.GeneratedProtocolMessageType('VersionRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREQUESTPB,
  '__module__' : 'ota_version_request_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.ota.VersionRequestPb)
  })
_sym_db.RegisterMessage(VersionRequestPb)


# @@protoc_insertion_point(module_scope)
