# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ota_version_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ota_version_info.proto',
  package='haomo.hidelivery.ota',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16ota_version_info.proto\x12\x14haomo.hidelivery.ota\x1a\x0cheader.proto\"H\n\rVersionInfoPb\x12\x13\n\x0bmoduel_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x11\n\tcommit_id\x18\x03 \x01(\t\"o\n\x0eVersionArrayPb\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.haomo.hios.Header\x12\x39\n\x0cversion_info\x18\x02 \x03(\x0b\x32#.haomo.hidelivery.ota.VersionInfoPbb\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,])




_VERSIONINFOPB = _descriptor.Descriptor(
  name='VersionInfoPb',
  full_name='haomo.hidelivery.ota.VersionInfoPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='moduel_name', full_name='haomo.hidelivery.ota.VersionInfoPb.moduel_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='haomo.hidelivery.ota.VersionInfoPb.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commit_id', full_name='haomo.hidelivery.ota.VersionInfoPb.commit_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=134,
)


_VERSIONARRAYPB = _descriptor.Descriptor(
  name='VersionArrayPb',
  full_name='haomo.hidelivery.ota.VersionArrayPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='haomo.hidelivery.ota.VersionArrayPb.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version_info', full_name='haomo.hidelivery.ota.VersionArrayPb.version_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=247,
)

_VERSIONARRAYPB.fields_by_name['header'].message_type = header__pb2._HEADER
_VERSIONARRAYPB.fields_by_name['version_info'].message_type = _VERSIONINFOPB
DESCRIPTOR.message_types_by_name['VersionInfoPb'] = _VERSIONINFOPB
DESCRIPTOR.message_types_by_name['VersionArrayPb'] = _VERSIONARRAYPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionInfoPb = _reflection.GeneratedProtocolMessageType('VersionInfoPb', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONINFOPB,
  '__module__' : 'ota_version_info_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.ota.VersionInfoPb)
  })
_sym_db.RegisterMessage(VersionInfoPb)

VersionArrayPb = _reflection.GeneratedProtocolMessageType('VersionArrayPb', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONARRAYPB,
  '__module__' : 'ota_version_info_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.ota.VersionArrayPb)
  })
_sym_db.RegisterMessage(VersionArrayPb)


# @@protoc_insertion_point(module_scope)
