# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='time_service.proto',
  package='haomo.hios',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12time_service.proto\x12\nhaomo.hios\x1a\x0cheader.proto\"\xd0\x01\n\rNtpTimeDataPb\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.haomo.hios.Header\x12\x13\n\x0bsys_time_us\x18\x02 \x01(\x04\x12\r\n\x05\x64\x65lay\x18\x03 \x01(\x01\x12\x0e\n\x06offset\x18\x04 \x01(\x01\x12\x30\n\x06status\x18\x05 \x01(\x0e\x32 .haomo.hios.NtpTimeDataPb.STATUS\"5\n\x06STATUS\x12\x08\n\x04NONE\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45ROOR\x10\x02\x12\x0e\n\nUSING_LAST\x10\x03\x62\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,])



_NTPTIMEDATAPB_STATUS = _descriptor.EnumDescriptor(
  name='STATUS',
  full_name='haomo.hios.NtpTimeDataPb.STATUS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EROOR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USING_LAST', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=204,
  serialized_end=257,
)
_sym_db.RegisterEnumDescriptor(_NTPTIMEDATAPB_STATUS)


_NTPTIMEDATAPB = _descriptor.Descriptor(
  name='NtpTimeDataPb',
  full_name='haomo.hios.NtpTimeDataPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='haomo.hios.NtpTimeDataPb.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sys_time_us', full_name='haomo.hios.NtpTimeDataPb.sys_time_us', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay', full_name='haomo.hios.NtpTimeDataPb.delay', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='haomo.hios.NtpTimeDataPb.offset', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='haomo.hios.NtpTimeDataPb.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NTPTIMEDATAPB_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=257,
)

_NTPTIMEDATAPB.fields_by_name['header'].message_type = header__pb2._HEADER
_NTPTIMEDATAPB.fields_by_name['status'].enum_type = _NTPTIMEDATAPB_STATUS
_NTPTIMEDATAPB_STATUS.containing_type = _NTPTIMEDATAPB
DESCRIPTOR.message_types_by_name['NtpTimeDataPb'] = _NTPTIMEDATAPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NtpTimeDataPb = _reflection.GeneratedProtocolMessageType('NtpTimeDataPb', (_message.Message,), {
  'DESCRIPTOR' : _NTPTIMEDATAPB,
  '__module__' : 'time_service_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hios.NtpTimeDataPb)
  })
_sym_db.RegisterMessage(NtpTimeDataPb)


# @@protoc_insertion_point(module_scope)
