# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import localization_pb2 as localization__pb2
import car_info_pb2 as car__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vehicle_state.proto',
  package='haomo.hidelivery.planning',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13vehicle_state.proto\x12\x19haomo.hidelivery.planning\x1a\x12localization.proto\x1a\x0e\x63\x61r_info.proto\"\xf5\x02\n\x0cVehicleState\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x0c\n\x04roll\x18\x05 \x01(\x01\x12\r\n\x05pitch\x18\x06 \x01(\x01\x12\x0b\n\x03yaw\x18\x07 \x01(\x01\x12\x0f\n\x07heading\x18\x08 \x01(\x01\x12\r\n\x05kappa\x18\t \x01(\x01\x12\x17\n\x0flinear_velocity\x18\n \x01(\x01\x12\x18\n\x10\x61ngular_velocity\x18\x0b \x01(\x01\x12\x1b\n\x13linear_acceleration\x18\x0c \x01(\x01\x12/\n\x04gear\x18\r \x01(\x0e\x32!.haomo.hios.GearBoxInfoPb.GearNum\x12\x31\n\x04pose\x18\x0e \x01(\x0b\x32#.haomo.hidelivery.localization.Pose\x12\x1b\n\x13steering_percentage\x18\x0f \x01(\x01\x12\x16\n\x0esteering_angle\x18\x10 \x01(\x01\x62\x06proto3'
  ,
  dependencies=[localization__pb2.DESCRIPTOR,car__info__pb2.DESCRIPTOR,])




_VEHICLESTATE = _descriptor.Descriptor(
  name='VehicleState',
  full_name='haomo.hidelivery.planning.VehicleState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='haomo.hidelivery.planning.VehicleState.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='haomo.hidelivery.planning.VehicleState.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='haomo.hidelivery.planning.VehicleState.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='haomo.hidelivery.planning.VehicleState.timestamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='haomo.hidelivery.planning.VehicleState.roll', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='haomo.hidelivery.planning.VehicleState.pitch', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='haomo.hidelivery.planning.VehicleState.yaw', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='haomo.hidelivery.planning.VehicleState.heading', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kappa', full_name='haomo.hidelivery.planning.VehicleState.kappa', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear_velocity', full_name='haomo.hidelivery.planning.VehicleState.linear_velocity', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='haomo.hidelivery.planning.VehicleState.angular_velocity', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear_acceleration', full_name='haomo.hidelivery.planning.VehicleState.linear_acceleration', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gear', full_name='haomo.hidelivery.planning.VehicleState.gear', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='haomo.hidelivery.planning.VehicleState.pose', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_percentage', full_name='haomo.hidelivery.planning.VehicleState.steering_percentage', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_angle', full_name='haomo.hidelivery.planning.VehicleState.steering_angle', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=460,
)

_VEHICLESTATE.fields_by_name['gear'].enum_type = car__info__pb2._GEARBOXINFOPB_GEARNUM
_VEHICLESTATE.fields_by_name['pose'].message_type = localization__pb2._POSE
DESCRIPTOR.message_types_by_name['VehicleState'] = _VEHICLESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VehicleState = _reflection.GeneratedProtocolMessageType('VehicleState', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLESTATE,
  '__module__' : 'vehicle_state_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.planning.VehicleState)
  })
_sym_db.RegisterMessage(VehicleState)


# @@protoc_insertion_point(module_scope)
