# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steer_offset.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='steer_offset.proto',
  package='haomo.hidelivery.planning',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x12steer_offset.proto\x12\x19haomo.hidelivery.planning\"f\n\x0fSreerOffsetUnit\x12\x13\n\x0bminVelocity\x18\x01 \x02(\x01\x12\x13\n\x0bmaxVelocity\x18\x02 \x02(\x01\x12\x13\n\x0bsteerOffset\x18\x03 \x02(\x01\x12\x14\n\x05\x62Init\x18\x04 \x02(\x08:\x05\x66\x61lse\"Y\n\x10SreerOffsetTable\x12\x45\n\x11steer_offset_unit\x18\x01 \x03(\x0b\x32*.haomo.hidelivery.planning.SreerOffsetUnit'
)




_SREEROFFSETUNIT = _descriptor.Descriptor(
  name='SreerOffsetUnit',
  full_name='haomo.hidelivery.planning.SreerOffsetUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minVelocity', full_name='haomo.hidelivery.planning.SreerOffsetUnit.minVelocity', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxVelocity', full_name='haomo.hidelivery.planning.SreerOffsetUnit.maxVelocity', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steerOffset', full_name='haomo.hidelivery.planning.SreerOffsetUnit.steerOffset', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bInit', full_name='haomo.hidelivery.planning.SreerOffsetUnit.bInit', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=151,
)


_SREEROFFSETTABLE = _descriptor.Descriptor(
  name='SreerOffsetTable',
  full_name='haomo.hidelivery.planning.SreerOffsetTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steer_offset_unit', full_name='haomo.hidelivery.planning.SreerOffsetTable.steer_offset_unit', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=242,
)

_SREEROFFSETTABLE.fields_by_name['steer_offset_unit'].message_type = _SREEROFFSETUNIT
DESCRIPTOR.message_types_by_name['SreerOffsetUnit'] = _SREEROFFSETUNIT
DESCRIPTOR.message_types_by_name['SreerOffsetTable'] = _SREEROFFSETTABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SreerOffsetUnit = _reflection.GeneratedProtocolMessageType('SreerOffsetUnit', (_message.Message,), {
  'DESCRIPTOR' : _SREEROFFSETUNIT,
  '__module__' : 'steer_offset_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.planning.SreerOffsetUnit)
  })
_sym_db.RegisterMessage(SreerOffsetUnit)

SreerOffsetTable = _reflection.GeneratedProtocolMessageType('SreerOffsetTable', (_message.Message,), {
  'DESCRIPTOR' : _SREEROFFSETTABLE,
  '__module__' : 'steer_offset_pb2'
  # @@protoc_insertion_point(class_scope:haomo.hidelivery.planning.SreerOffsetTable)
  })
_sym_db.RegisterMessage(SreerOffsetTable)


# @@protoc_insertion_point(module_scope)
